export const client = String.raw`
const $=id=>document.getElementById(id);
let profile=null,current=null,view='overview',offset=0,nextOffset=null,catalog=[],dashboard=null,libraryRequest=0;
const views={overview:['My work','Your saved work, across the Lab.'],archive:['Library','Find, reopen and keep work from your connected applications.'],applications:['Applications','One place to return to the tools you use.'],settings:['Settings','Your preferences for a shared workspace.']};
const icons={overview:'M8 4h8v4H8z M6 6H4v16h16V6h-2 M8 12h8 M8 16h6',archive:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3z M12 6v16',applications:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',settings:'M12 3v3 M12 18v3 M3 12h3 M18 12h3 M5.6 5.6l2.1 2.1 M16.3 16.3l2.1 2.1 M5.6 18.4l2.1-2.1 M16.3 7.7l2.1-2.1 M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10',folder:'M2 6h8l3 3h9v12H2z',pin:'M9 3h6l-1 7 5 5H5l5-5z M12 15v7'};
function icon(name,cls='nav-icon'){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class',cls);svg.setAttribute('aria-hidden','true');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.5');svg.setAttribute('stroke-linejoin','round');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',icons[name]||icons.folder);svg.append(path);return svg;}
for(const b of document.querySelectorAll('[data-view]'))b.prepend(icon(b.dataset.view));
function nameFor(id){return catalog.find(app=>app.id===id)?.name||id;}
function status(text){$('status').textContent=text;}
function dark(){return document.documentElement.dataset.theme?document.documentElement.dataset.theme==='dark':matchMedia('(prefers-color-scheme: dark)').matches;}
function theme(){const isDark=dark();$('theme-toggle').textContent=isDark?'Light theme':'Dark theme';$('theme-toggle').setAttribute('aria-pressed',String(isDark));}
$('theme-toggle').onclick=()=>{const next=dark()?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('cail-desk-theme',next)}catch{}theme();};theme();matchMedia('(prefers-color-scheme: dark)').addEventListener('change',theme);
async function api(path,method='GET',body){const r=await fetch('/my-work/api'+path,{method,headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'This operation could not be completed.');return d;}
function syncControls(){$('previous').disabled=offset===0;$('next').disabled=nextOffset===null;}
function guarded(fn){return async event=>{event?.preventDefault();const button=event?.currentTarget?.tagName==='BUTTON'?event.currentTarget:null;if(button?.dataset.busy)return;if(button){button.dataset.busy='true';button.disabled=true;}try{await fn(event);}catch(e){status(e.message);}finally{if(button){delete button.dataset.busy;button.disabled=false;}syncControls();}};}
function date(ms){return new Date(ms).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function empty(container,title,copy,kind='folder',launch=false){const el=document.createElement('div');el.className='empty';el.append(icon(kind,'empty-icon'));const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=copy;el.append(h,p);if(launch){const app=catalog.find(a=>a.connection==='connected');if(app){const a=document.createElement('a');a.href=app.href;a.textContent='Open '+app.name;el.append(a);}}container.append(el);}
function list(container,items){for(const item of items){const row=document.createElement('article');row.className='record';const content=document.createElement('div');content.className='record-main';const b=document.createElement('button');b.className='record-title';b.textContent=item.title;b.onclick=guarded(()=>openItem(item.id));const small=document.createElement('small');small.textContent=nameFor(item.app)+' · '+date(item.updatedAt)+' · Revision '+item.revision;const tag=document.createElement('span');tag.className='record-tag';tag.textContent=item.pinned?'Pinned':item.kind;content.append(b,small);row.append(content,tag);container.append(row);}}
function directory(container){container.replaceChildren();for(const app of catalog){const tile=document.createElement('article');tile.className='app-tile';const head=document.createElement('div');head.className='app-tile-head';const symbol=document.createElement('span');symbol.className='app-symbol';symbol.setAttribute('aria-hidden','true');symbol.textContent=app.name.slice(0,1);const text=document.createElement('div');const h=document.createElement('h3');h.textContent=app.name;const connection=document.createElement('div');connection.className='connection '+app.connection;connection.textContent=app.connection==='connected'?'● Connected':'Workspace connection planned';text.append(h,connection);head.append(symbol,text);const p=document.createElement('p');p.textContent=app.description;tile.append(head,p);if(app.href){const a=document.createElement('a');a.href=app.href;a.textContent='Open '+app.name;tile.append(a);}else{const note=document.createElement('p');note.className='hint';note.textContent='Not yet available in My work.';tile.append(note);}container.append(tile);}}
async function loadCatalog(){const d=await api('/applications');catalog=d.applications;for(const id of ['recent-app','archive-app','default-app'])for(const app of catalog){const opt=document.createElement('option');opt.value=app.id;opt.textContent=app.name;$(id).append(opt);}for(const item of d.labLinks){const a=document.createElement('a');a.href=item.href;a.textContent=item.label;const small=document.createElement('small');small.textContent=item.description;a.append(small);$('lab-links').append(a);}directory($('app-cards'));directory($('application-directory'));}
function renderRecent(){if(!dashboard)return;const filter=$('recent-app').value;const sets=Object.entries(dashboard.apps).filter(([app])=>filter==='all'||app===filter).map(([,set])=>set);const recent=sets.flatMap(set=>set.recent).sort((a,b)=>b.updatedAt-a.updatedAt||a.id.localeCompare(b.id));const pins=sets.flatMap(set=>set.pinned).sort((a,b)=>b.updatedAt-a.updatedAt||a.id.localeCompare(b.id));$('recent-list').replaceChildren();$('pinned-list').replaceChildren();if(recent.length)list($('recent-list'),recent);else empty($('recent-list'),pins.length?'No unpinned work':'No saved work yet',pins.length?'Your pinned work is kept separately.':'Work from connected applications appears here.','folder',true);if(pins.length)list($('pinned-list'),pins);else empty($('pinned-list'),'Nothing pinned yet','Pin saved work to keep it here.','pin');}
async function loadOverview(){dashboard=await api('/dashboard');renderRecent();}
async function loadArchive(){const request=++libraryRequest;const params=new URLSearchParams({app:$('archive-app').value,offset:String(offset),q:$('archive-search').value});if($('archive-pins').value)params.set('pinned',$('archive-pins').value);const d=await api('/entries?'+params);if(request!==libraryRequest)return;$('archive-list').replaceChildren();if(d.items.length)list($('archive-list'),d.items);else empty($('archive-list'),'No work in this view','Try another application or search, or open a connected application to begin.');nextOffset=d.nextOffset;$('page-number').textContent='Page '+(Math.floor(offset/20)+1);syncControls();}
async function loadSettings(){profile=(await api('/profile')).profile;$('display-name').value=profile.displayName;$('default-app').value=profile.defaultApp;$('account-name').textContent=profile.displayName?'Workspace for '+profile.displayName:'';$('account-name').hidden=!profile.displayName;}
function changed(){return current&&($('item-title').value!==current.title||$('item-text').value!==current.content.text||$('item-reading').value!==current.content.reading);}
function canLeave(){return !changed()||confirm('Leave without saving your changes?');}
function displayView(name){for(const id of Object.keys(views))$(id).hidden=id!==name;$('detail').hidden=true;document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('page-title').textContent=views[name][0];$('page-description').textContent=views[name][1];}
function routeHash(){const q=new URLSearchParams;if(current)q.set('work',current.id);history.replaceState(null,'',location.pathname+(q.size?'?'+q:'')+'#'+view);}
async function setView(name){if(!views[name]||!canLeave())return;view=name;current=null;status('');displayView(name);routeHash();if(name==='overview')await loadOverview();if(name==='archive')await loadArchive();if(name==='settings')await loadSettings();}
for(const b of document.querySelectorAll('[data-view]'))b.onclick=guarded(()=>setView(b.dataset.view));
$('explore').onclick=$('browse-apps').onclick=guarded(()=>setView('applications'));$('recent-app').onchange=renderRecent;
$('browse-pins').onclick=guarded(async()=>{offset=0;$('archive-app').value=$('recent-app').value;$('archive-pins').value='1';$('archive-search').value='';await setView('archive');});
async function openItem(id){if(!canLeave())return;const item=(await api('/entries/'+encodeURIComponent(id))).item;current=item;for(const name of Object.keys(views))$(name).hidden=true;$('detail').hidden=false;$('detail-heading').textContent=current.title;$('item-title').value=current.title;$('item-text').value=current.content.text;$('item-reading').value=current.content.reading;$('detail-meta').textContent=nameFor(current.app)+' · '+current.kind+' · Revision '+current.revision+' · '+date(current.updatedAt);$('pin').textContent=current.pinned?'Unpin':'Pin privately';$('item-records').textContent=JSON.stringify({contributions:current.content.contributions,settings:current.content.settings,record:current.content.record},null,2);const app=catalog.find(a=>a.id===current.app);$('continue').hidden=!app?.resumePath;if(app?.resumePath){$('continue').href=app.resumePath+'?work='+encodeURIComponent(current.id);$('continue').textContent='Continue in '+app.name;}$('delete-item-confirm').hidden=true;routeHash();$('detail-heading').scrollIntoView({block:'start'});}
$('back').onclick=guarded(()=>setView(view));$('continue').onclick=e=>{if(!canLeave())e.preventDefault();};window.addEventListener('beforeunload',e=>{if(changed()){e.preventDefault();e.returnValue='';}});
$('archive-app').onchange=$('archive-pins').onchange=$('search-form').onsubmit=guarded(async()=>{offset=0;await loadArchive();});let searchTimer;$('archive-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>guarded(async()=>{offset=0;await loadArchive();})(),250);};$('next').onclick=guarded(async()=>{offset=nextOffset;await loadArchive();});$('previous').onclick=guarded(async()=>{offset=Math.max(0,offset-20);await loadArchive();});
$('settings-form').onsubmit=guarded(async()=>{await api('/profile','PATCH',{displayName:$('display-name').value,defaultApp:$('default-app').value,expectedRevision:profile.revision});await loadSettings();$('archive-app').value=profile.defaultApp;offset=0;status('Settings saved and verified.');});$('export').onclick=guarded(async()=>download('cail-my-work.json',await api('/export')));$('delete-account').onclick=guarded(async()=>{await api('/account-data','DELETE',{confirmation:$('delete-confirm').value});$('delete-confirm').value='';await loadSettings();await setView('overview');status('Your workspace data was deleted.');});
$('pin').onclick=guarded(async()=>{if(!canLeave())return;const id=current.id;await api('/entries/'+id+'/pin','PATCH',{pinned:!current.pinned,expectedRevision:current.revision});current=null;await openItem(id);status(current.pinned?'Pinned privately.':'Unpinned.');});$('save-item').onclick=guarded(async()=>{const id=current.id;await api('/entries','PUT',{id,app:current.app,kind:current.kind,title:$('item-title').value,content:{...current.content,text:$('item-text').value,reading:$('item-reading').value},expectedRevision:current.revision});current=null;await openItem(id);status('Changes saved.');});$('download-item').onclick=()=>download('cail-work-'+current.id+'.json',current);$('delete-item').onclick=()=>{$('delete-item-confirm').hidden=false;};$('confirm-delete-item').onclick=guarded(async()=>{await api('/entries/'+current.id,'DELETE',{expectedRevision:current.revision});current=null;await setView(view);status('Saved item deleted.');});
(async()=>{try{await loadCatalog();await loadSettings();$('archive-app').value=profile.defaultApp;const requested=location.hash.slice(1);view=views[requested]?requested:'overview';const id=new URLSearchParams(location.search).get('work');if(id){displayView(view);await openItem(id);}else await setView(view);}catch(e){status(e.message);}})();
`;
