import { styles } from './ui-styles.ts';
import { client } from './ui-client.ts';
export const page = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My work · CUNY AI Lab</title><script>try{const t=localStorage.getItem('cail-desk-theme');if(t==='light'||t==='dark')document.documentElement.dataset.theme=t}catch{}</script><style>${styles}</style></head><body>
<a class="skip" href="#main">Skip to workspace</a><header class="commandbar"><a class="brand" href="/my-work/"><span class="brand-mark" aria-hidden="true"></span>CUNY AI Lab</a><div class="command-actions"><a href="https://tools.ailab.gc.cuny.edu/welcome">Lab access</a><button id="theme-toggle" type="button">Dark theme</button></div></header>
<div class="shell"><aside class="sidebar"><nav class="workspace-nav" aria-label="Workspace"><button data-view="overview" aria-current="page">My work</button><button data-view="archive">Library</button><button data-view="applications">Applications</button><button data-view="settings">Settings</button></nav><nav class="lab-navigation" aria-label="Lab links"><h2>Lab links</h2><div id="lab-links"></div></nav></aside>
<main id="main" tabindex="-1"><header class="page-head"><div><h1 id="page-title">My work</h1><p id="page-description">Your saved work, across the Lab.</p><p id="account-name" hidden></p></div><button class="text-button" id="explore">Browse applications</button></header><p id="status" role="status" aria-live="polite"></p>
<div id="overview"><div class="overview-grid"><section class="panel" aria-labelledby="recent-title"><div class="panel-head"><h2 id="recent-title">Recent work</h2><select id="recent-app" aria-label="Filter recent work by application"><option value="all">All applications</option></select></div><div class="panel-body"><div id="recent-list"></div><p class="hint">Five recent unpinned items per application. Older work stays in your library.</p></div></section><section class="panel" aria-labelledby="pinned-title"><div class="panel-head"><h2 id="pinned-title">Pinned work</h2><button class="text-button" id="browse-pins">View all pins</button></div><div class="panel-body" id="pinned-list"></div></section></div><section class="panel directory" aria-labelledby="directory-title"><div class="panel-head"><h2 id="directory-title">Applications</h2><button class="text-button" id="browse-apps">View directory</button></div><div id="app-cards" class="directory-grid"></div></section></div>
<div id="archive" hidden><section class="panel" aria-label="Saved work library"><form class="filters" id="search-form"><div><label for="archive-search">Search titles</label><input type="search" id="archive-search" maxlength="120" placeholder="Find saved work…"></div><div><label for="archive-app">Application</label><select id="archive-app"><option value="all">All applications</option></select></div><div><label for="archive-pins">Show</label><select id="archive-pins"><option value="">All saved work</option><option value="1">Pinned</option><option value="0">Unpinned</option></select></div></form><div class="panel-body" id="archive-list"></div></section><div class="pagination"><button id="previous">Previous page</button><span id="page-number" class="muted"></span><button id="next">Next page</button></div></div>
<div id="applications" hidden><section class="panel"><div class="panel-head"><h2>Applications and games</h2></div><p class="directory-intro">Open a tool to begin or continue work. Connected applications save here; other applications keep their work in their own workspace.</p><div class="directory-grid" id="application-directory"></div><div class="directory-note">Cadavre is the first connected application. New applications can join this shared workspace as their connections are added.</div></section></div>
<div id="settings" hidden><div class="settings-grid"><section class="panel settings-panel"><h2>Workspace preferences</h2><p>Signed in through CUNY. These settings apply across your connected applications.</p><form id="settings-form" class="form-stack"><div><label for="display-name">Display name</label><input id="display-name" maxlength="80" autocomplete="nickname"></div><div><label for="default-app">Default library view</label><select id="default-app"><option value="all">All applications</option></select></div><div><button class="primary" type="submit">Save settings</button></div></form></section><div><section class="panel settings-panel"><h2>Take your work with you</h2><p>Download your settings, saved work and related records as JSON.</p><button id="export">Export my work</button></section><section class="panel settings-panel"><details><summary>Delete workspace data</summary><p>This removes saved work and related records from this workspace. Your CUNY login and Lab membership remain.</p><label for="delete-confirm">Type DELETE MY WORK</label><input id="delete-confirm" autocomplete="off"><p><button id="delete-account" class="danger">Delete my workspace data</button></p></details></section></div></div></div>
<section class="panel detail" id="detail" hidden aria-labelledby="detail-heading"><div class="actions"><button id="back">Back to my work</button><button id="pin">Pin</button><button id="download-item">Export item</button><a id="continue" class="button" hidden>Continue in application</a></div><h2 id="detail-heading">Saved work</h2><p id="detail-meta" class="muted"></p><div class="form-stack"><div><label for="item-title">Title</label><input id="item-title" maxlength="120"></div><div><label for="item-text">Work</label><textarea id="item-text"></textarea></div><div><label for="item-reading">Notes</label><textarea id="item-reading"></textarea></div><details><summary>Contributions and related records</summary><pre id="item-records"></pre></details><div class="actions"><button id="save-item" class="primary">Save changes</button><button id="delete-item" class="danger">Delete item</button></div><p id="delete-item-confirm" hidden>Delete this saved item and its related records? <button id="confirm-delete-item">Confirm deletion</button></p></div></section>
<footer class="footer">CUNY AI Lab</footer></main></div><script>${client}</script></body></html>`;
