// Only browser-local public-wall capabilities and settings move here. Private
// accounts stay in D1; session cookies and model credentials are never copied.
const oldOrigin='https://cail-cadavre.ailab-452.workers.dev';
const newOrigin='https://cadavre.ailab-452.workers.dev';
const keys=['cadavreWall','cadavreWallDeleteTokens','cadavreWallVoterToken','cadavreWallVotes','cadavreWallReadings','corpse.settings','corpse.library'];
function page(body:string,script:string){return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cadavre · CUNY AI Lab</title><style>body{font:17px/1.6 system-ui;color:#172c3e;background:#f4f5f2;max-width:38rem;margin:10vh auto;padding:2rem}a{color:#235e65}button{font:inherit;color:#235e65;border:1px solid #bac6c5;background:transparent;border-radius:4px;padding:.4rem .7rem;cursor:pointer}small{color:#536773}</style><header><small>CUNY AI Lab</small></header>${body}<p id="status" role="status"></p><script>${script}</script></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','referrer-policy':'no-referrer','x-content-type-options':'nosniff','content-security-policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"}});}
export function retiredCadavre(){return page(`<h1>Cadavre has moved</h1><p><a href="${newOrigin}/">Open Cadavre</a></p><p>Your poems and My work are kept.</p><p><button id="move">Bring this browser’s wall edits</button></p><small>This keeps your ability to edit public-wall poems posted from this browser.</small>`, `
const target=${JSON.stringify(newOrigin)},keys=${JSON.stringify(keys)};let destination;
document.getElementById('move').onclick=()=>{destination=window.open(target+'/move','cadavre-move');document.getElementById('status').textContent=destination?'Continue in the new window.':'Allow the new window, then try again.';};
window.addEventListener('message',event=>{if(event.origin!==target||event.source!==destination||event.data?.type!=='cadavre-move-ready')return;const values={};let partial=false;try{for(const key of keys){const value=localStorage.getItem(key);if(value!==null){if(value.length<=500000)values[key]=value;else partial=true;}}destination.postMessage({type:'cadavre-browser-move',values,partial},target);}catch{document.getElementById('status').textContent='Browser storage is unavailable. Try again in the browser you used before.';}});
`);}
export function receiveBrowserMove(){return page(`<h1>Keep your wall edits</h1><p id="instructions">Receiving this browser’s public-wall edits and settings from the old address.</p><p><a href="/">Continue to Cadavre</a></p>`, `
const source=${JSON.stringify(oldOrigin)},keys=${JSON.stringify(keys)};let received=false;
window.addEventListener('message',event=>{if(received||event.origin!==source||event.source!==window.opener||event.data?.type!=='cadavre-browser-move')return;const values=event.data.values;if(!values||typeof values!=='object'||Array.isArray(values))return;try{for(const key of keys){const incoming=values[key];if(typeof incoming!=='string'||incoming.length>500000)continue;const current=localStorage.getItem(key);if(current===null){localStorage.setItem(key,incoming);continue;}if(key==='cadavreWallDeleteTokens'||key==='cadavreWallVotes'||key==='cadavreWallReadings'){const old=JSON.parse(incoming),now=JSON.parse(current);if(old&&now&&typeof old==='object'&&typeof now==='object'&&!Array.isArray(old)&&!Array.isArray(now))localStorage.setItem(key,JSON.stringify({...old,...now}));}}received=true;document.getElementById('status').textContent=event.data.partial?'Some large browser records were not copied. The old browser storage is still kept.':'Your wall edits are available here. The old browser storage has also been kept.';}catch{document.getElementById('status').textContent='Some browser storage could not be copied. The old storage is still kept; try again.';}});
if(window.opener)window.opener.postMessage({type:'cadavre-move-ready'},source);else document.getElementById('instructions').textContent='Open the old Cadavre address and choose “Bring this browser’s wall edits”.';
`);}
