"""Genre-balance diagnostic (Known follow-up #3).

Reports how much of the corpus is the surreal/modernist *core*
(`poetrydb` + `gutenberg` volumes) versus the down-weighted Gutenberg Poetry
Corpus *padding* (`gpc`) — at both the poem level and the next-line-example
level — and shows what different `--gpc-ratio` caps would do to GPC's share of
the training set. There is no separate genre tag on records; the **source
family** (``source.split(":")[0]``) is the genre proxy, exactly as
`build_dataset`/`clean` treat it.

To stay drift-proof, this imports the *real* slicing/splitting logic from
`build_dataset` instead of reimplementing it, so the counts here provably match
an actual rebuild (they reproduce `data/processed/dataset_stats.json`).

    python -m src.report_balance                 # print report
    python -m src.report_balance --write-md      # also write docs/genre-balance.md
"""
from __future__ import annotations

import argparse
from collections import Counter

from src.build_dataset import examples_for, poem_split
from src.common import INTERIM, ROOT, read_jsonl

POEMS = INTERIM / "poems.jsonl"
REPORT_MD = ROOT / "docs" / "genre-balance.md"

# gpc-ratio candidates to preview (default build uses 0.5)
RATIO_GRID = [0.25, 0.33, 0.5, 1.0]


def family(source: str) -> str:
    return str(source).split(":")[0]


def is_gpc(source: str) -> bool:
    return str(source).startswith("gpc")


def collect(val_frac: float, max_ctx_lines: int):
    """Return per-family poem/example tallies mirroring build_dataset."""
    poems_by_fam: Counter = Counter()
    core_train_ex = 0        # non-gpc, split==train examples
    core_val_ex = 0          # non-gpc, split==val examples
    gpc_train_ex = 0         # gpc, split==train examples (val-excluded upstream)
    ex_by_fam: Counter = Counter()  # total emittable examples per family
    for poem in read_jsonl(POEMS):
        fam = family(poem["source"])
        poems_by_fam[fam] += 1
        split = poem_split(poem["id"], val_frac)
        n = len(examples_for(poem, max_ctx_lines))
        ex_by_fam[fam] += n
        if is_gpc(poem["source"]):
            if split == "train":
                gpc_train_ex += n
        elif split == "val":
            core_val_ex += n
        else:
            core_train_ex += n
    return poems_by_fam, ex_by_fam, core_train_ex, core_val_ex, gpc_train_ex


def used_and_share(core_train: int, gpc_avail: int, ratio: float):
    cap = int(core_train * ratio)
    used = min(gpc_avail, cap)
    total = core_train + used
    share = used / total if total else 0.0
    return used, share, used < gpc_avail  # capped?


def render(pf: Counter, ef: Counter, core_train: int, core_val: int,
           gpc_avail: int, val_frac: float, max_ctx: int, default_ratio: float):
    total_poems = sum(pf.values())
    core_poems = sum(v for k, v in pf.items() if k != "gpc")
    gpc_poems = pf.get("gpc", 0)
    used, share, capped = used_and_share(core_train, gpc_avail, default_ratio)

    L = []
    L.append("# Genre balance — core vs. GPC padding\n")
    L.append("_Generated by `python -m src.report_balance`. The **source family** is the "
             "genre proxy: `poetrydb` + `gutenberg` = surreal/modernist core; `gpc` = "
             "down-weighted Gutenberg-Poetry-Corpus padding (never in val)._\n")
    L.append(f"- val split: `{val_frac}` · max ctx lines: `{max_ctx}` · "
             f"default `--gpc-ratio`: `{default_ratio}`\n")

    L.append("## Poems after clean (by source family)\n")
    L.append("| family | poems | share |")
    L.append("|---|--:|--:|")
    for fam, n in pf.most_common():
        L.append(f"| {fam} | {n:,} | {n/total_poems:.1%} |")
    L.append(f"| **core (non-gpc)** | **{core_poems:,}** | **{core_poems/total_poems:.1%}** |")
    L.append(f"| **all** | **{total_poems:,}** | 100% |\n")

    L.append("## Emittable next-line examples (before the gpc cap)\n")
    L.append("| family | examples |")
    L.append("|---|--:|")
    for fam, n in ef.most_common():
        L.append(f"| {fam} | {n:,} |")
    L.append(f"| **core train** | **{core_train:,}** |")
    L.append(f"| **core val** | **{core_val:,}** |")
    L.append(f"| **gpc train (available)** | **{gpc_avail:,}** |\n")

    L.append("## What each `--gpc-ratio` cap yields for the training set\n")
    L.append("GPC is subsampled to at most `ratio × core_train` examples; val is core-only.\n")
    L.append("| gpc-ratio | gpc used | train total | gpc share | capped? |")
    L.append("|--:|--:|--:|--:|:--:|")
    for r in RATIO_GRID:
        u, sh, cap = used_and_share(core_train, gpc_avail, r)
        mark = "yes" if cap else "no (all GPC fits)"
        star = " ⟵ current" if abs(r - default_ratio) < 1e-9 else ""
        L.append(f"| {r:g}{star} | {u:,} | {core_train + u:,} | {sh:.1%} | {mark} |")
    L.append("")

    L.append("## Read\n")
    dominates = share >= 0.5
    L.append(f"- At the current `--gpc-ratio {default_ratio:g}`, GPC padding is "
             f"**{share:.1%}** of the training examples "
             f"(core outnumbers it {core_train/used:.1f}:1)." if used else
             "- No GPC examples in the training set.")
    L.append(f"- GPC **{'DOES' if dominates else 'does not'} dominate** "
             f"(threshold = 50% of train examples).")
    if dominates:
        L.append("- **Action:** lower `--gpc-ratio` in `build_dataset`, then rerun "
                 "`src.build_dataset` (and retrain to make it take effect).")
    else:
        L.append("- **Action:** none — the surreal/modernist core already dominates; "
                 "leave `--gpc-ratio` at its default. Lowering it would only trade away "
                 "breadth without changing which genre leads.")
    L.append("")
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--val-frac", type=float, default=0.05)
    ap.add_argument("--max-ctx-lines", type=int, default=24)
    ap.add_argument("--gpc-ratio", type=float, default=0.5,
                    help="the ratio the shipped dataset was built with (for the ⟵ marker)")
    ap.add_argument("--write-md", action="store_true", help="also write docs/genre-balance.md")
    args = ap.parse_args()

    if not POEMS.exists():
        raise SystemExit("run src.clean first")

    pf, ef, core_train, core_val, gpc_avail = collect(args.val_frac, args.max_ctx_lines)
    report = render(pf, ef, core_train, core_val, gpc_avail,
                    args.val_frac, args.max_ctx_lines, args.gpc_ratio)
    print(report)
    if args.write_md:
        REPORT_MD.write_text(report)
        print(f"\nwrote {REPORT_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
